model:
  bedrock:
    # model_id: anthropic.claude-3-sonnet-20240229-v1:0
    model_id: anthropic.claude-3-5-sonnet-20240620-v1:0
    # model_id: anthropic.claude-3-haiku-20240307-v1:0
    region: us-east-1
    aws_profile: my-aws-bedrock
